name: 'GitHub Actions Pytests'

on: push

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- name: "checkout"
				uses: actions/checkout@v2

			- name: "setup"
				uses: actions/setup-python@v2

			-	name: install dependencies
				run: | 
					python -m pip install --upgrade pip 
					pip install pytest
					pip install black
      		if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
					


